pub(crate) const TPCH_QUERY_TEXTS: &[(i32, &str)] = &[
    (1, include_str!("../queries/q01.sql")),
    (2, include_str!("../queries/q02.sql")),
    (3, include_str!("../queries/q03.sql")),
    (4, include_str!("../queries/q04.sql")),
    (5, include_str!("../queries/q05.sql")),
    (6, include_str!("../queries/q06.sql")),
    (7, include_str!("../queries/q07.sql")),
    (8, include_str!("../queries/q08.sql")),
    (9, include_str!("../queries/q09.sql")),
    (10, include_str!("../queries/q10.sql")),
    (11, include_str!("../queries/q11.sql")),
    (12, include_str!("../queries/q12.sql")),
    (13, include_str!("../queries/q13.sql")),
    (14, include_str!("../queries/q14.sql")),
    (15, include_str!("../queries/q15.sql")),
    (16, include_str!("../queries/q16.sql")),
    (17, include_str!("../queries/q17.sql")),
    (18, include_str!("../queries/q18.sql")),
    (19, include_str!("../queries/q19.sql")),
    (20, include_str!("../queries/q20.sql")),
    (21, include_str!("../queries/q21.sql")),
    (22, include_str!("../queries/q22.sql")),
];
